version: "3.8"

services:
    mysql:
        image: mariadb:10.8.3
        command:
            - --default-authentication-plugin=mysql_native_password
            - --skip-name-resolve
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: "%"
            MYSQL_USER: l*****l
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: book_review
        ports:
            - "3308:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "r***", "-***"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - laravel_network

    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: book_review
            DB_USERNAME: l****l
            DB_PASSWORD: secret
        volumes:
            - .:/var/www/html
        expose:
            - "9000"  # Critical for Nginx connection
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - laravel_network

    webserver:
        image: nginx:alpine
        ports:
            - "8000:80"  # Host:Container port mapping
        volumes:
            - ./:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel
        networks:
            - laravel_network

volumes:
    mysql_data:

networks:
    laravel_network:
        driver: bridge
